<?php

########################################################################
# Extension Manager/Repository config file for ext: "feusers_reminder"
#
# Auto generated by Extension Builder 2012-11-21
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FE User Reminder',
	'description' => 'Implemented a cron job for the TYPO3 scheduler. All users who have not confirmed their account receive, via e-mail a reminder to complete the registration.',
	'category' => 'be',
	'author' => 'Christian Wolfram, Marc Fell',
	'author_email' => 'c.wolfram@chriwo.de, info@marc-fell.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => 'fe_users',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
			'scheduler' => '1.2.0-1.2.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>